### ISSUE TITLE
About MIME types

### ISSUE THREAD

**Issue by Nhowka** [SaturnFramework/Saturn#100]
I was testing some PWA features and it was ok with `use_static` until I added a `manifest.webmanifest` file. That was not being served, failing with 404 error.

After some research, I found [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files#fileextensioncontenttypeprovider) that made me add the following code to the `application`:

```
    app_config (fun app ->
        let provider = FileExtensionContentTypeProvider()
        provider.Mappings.[".webmanifest"] <- "application/manifest+json"
        app.UseStaticFiles(StaticFileOptions(ContentTypeProvider=provider)))
```

It works, but not very friendly. Should we add a new operation to add MIME types?

A possible implementation could be:

```
[<CustomOperation("add_mime_type")>]
member __.AddMimeType(state,extension,mimeType) =
    // Add a new field `mimeTypes : (string * string) list` to `ApplicationState`
    {state with mimeTypes = (extension,mimeType)::state.mimeTypes}
```

Changing
https://github.com/SaturnFramework/Saturn/blob/6cb47c57f9dd1dec5b66a2920679f9f858aeb27e/src/Saturn/Application.fs#L135
to
```
let middleware (app : IApplicationBuilder) =
    match app.UseDefaultFiles(), state.mimeTypes with
    | (app,[]) -> app.UseStaticFiles()
    | (app,mimes) ->
        let provider = FileExtensionContentTypeProvider()
        mimes |> List.iter (fun (extension, mime) -> provider.Mappings.[extension] <- mime)
        app.UseStaticFiles(StaticFileOptions(ContentTypeProvider=provider)))
```

**Comment by Krzysztof-Cieslak** [comment]
In general this would be fine addition. But maybe `add_mime_types` that takes `(string * string) list` (or map) - so you don't need to call `add_mime_type` multiple times, but just pass map with all the custom mappings?

**Comment by Nhowka** [comment]
Even better!

**Comment by Krzysztof-Cieslak** [comment]
PR welcomed ;-)

**Comment by Thorium** [comment]
Just as a documentation for others trying this feature, the correct syntax is:
```fsharp
let app =
    application {
        use_mime_types [".yml", "application/x-yaml"]
        use_static serverPath
    }
```
- If you type just "yml", it doesn't work, the dot is needed.
- This will serve both the normal files and yml-files, not only-yml-files.
