### ISSUE TITLE
When creating a sample application from template 0.7.3, application appears to generate malformed routes

### ISSUE THREAD

**Issue by drk-mtr** [SaturnFramework/Saturn#108]
# System Info

Chrome 67 / Firefox 60
Windows 10
Saturn 0.7.3
Dotnet Core 2.1.300

# Repro Steps

1. Follow this guide `https://saturnframework.github.io/docs/guides/how-to-start/`
1. Add a book by visiting `http://localhost:8085/books` and clicking `New Book`
1. Enter info in fields and click to `Submit`
1. Error 404 received as the URL is `http://localhost:8085/books//` (though we can see the book is successfully added when manually navigating back to the `http://localhost:8085/books` page)
1. Similarly, when on the `http://localhost:8085/books` page, going to `Show` and then `Back` will rewrite URL as `http://localhost:8085/books/` 

# Notes

I have had this working without issue using a previous build of Saturn and was really impressed by the framework, so I suspect the resolution is rather simple, however I'm too new to F# to help fix this - sorry!

**Comment by NinoFloris** [comment]
@Krzysztof-Cieslak May have something to do with double registration of "resource/" routes (with another one for "resource") as we unconditionally do `ctx.Request.Path <- PathString(ctx.Request.Path.ToString() + "/");`

**Comment by Krzysztof-Cieslak** [comment]
Yeah, I think that before refactoring changing path was happening only for one case

**Comment by NinoFloris** [comment]
Yep mea culpa, will send a PR

**Comment by drk-mtr** [comment]
You guys are responding to issues faster than a commercial company would... very impressive!
