### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by tesserakt** [SaturnFramework/Saturn#119]
I am curious as to how to get a JSON API (http://jsonapi.org/) compliant server using Saturn?

**Comment by Krzysztof-Cieslak** [comment]
I don't really think it's in scope of the Saturn itself, you can use any of .Net libraries handling JSON API to serialize/model your data and then simply return them from the Saturn handlers

Some links to the libraries:
* https://github.com/codecutout/JsonApiSerializer
* https://github.com/scott-mcdonald/JsonApiFramework
