### ISSUE TITLE
Versioning and naming convention for extension packages

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/Saturn#120]
Some of the functionalities, while I'm happy to have in this repository, I think shouldn't be placed in core Saturn library but rather in separate NuGet packages. As for now there exist 2 additional projects - one for HttpSys hosting, and second one for integration with 3rd party OAuth providers.

1. What should be naming convention? (atm, OAuth is named `Saturn.Extensions.Authorization`, and HttpSys is named `Saturn.HttpSys`)
2. What should be namespace/modules naming convention?
3. What should be versioning story (independent? all packages released at same time with same version as core?
4. What should be release notes story? (again, independent? or just include it in main release notes?)

Opinions and discussion welcomed :-)

**Comment by rmunn** [comment]
I only have an opinion on the versioning right now, which is that all the packages that come from the same source repo should probably be released as the same version. So if going from 0.7.3 to 0.7.4 only has changes in `Saturn`, there should be an 0.7.4 release of the `Saturn.Extensions.Authorization` package as well even though its 0.7.4 will be identical to 0.7.3.

**Comment by Krzysztof-Cieslak** [comment]
OK, current plan:
* use `Saturn.Extensions.XXX` for most packages, `Saturn.XXX` for bigger ones (currently AzureFunctions, not sure if there will be any others soon)
* Use common version
* Use single release notes

This is easiest one to manage, and understand. It can be revisited if we reach some huge number of extensions and contributors
