### ISSUE TITLE
Adding Saturn.Extensions.Authorization via paket.

### ISSUE THREAD

**Issue by sashang** [SaturnFramework/Saturn#127]
I'd like to try the use_google_oauth functionality but I can't add it via paket. At the moment I have Saturn 0.7.4 added to my project but the Saturn.Extensions.Authorization.dll isn't included. Do I have to manually add it somehow?
```
.paket/paket.exe show-installed-packages
Paket version 5.176.1
Build Fake.Core.Target - 5.2
Build Fake.DotNet.Cli - 5.2
Build Fake.IO.FileSystem - 5.2
Build FSharp.Core - 4.3.4
Client dotnet-fable - 1.3.17
Client Fable.Core - 1.3.17
Client Fable.Elmish.Browser - 1.0
Client Fable.Elmish.Debugger - 1.0.1
Client Fable.Elmish.HMR - 1.0
Client Fable.Elmish.React - 1.0.3
Client Fulma - 1.0.0-beta-025
Client Fulma.Extensions - 1.0.0-beta-016
Server dotnet-fable - 1.3.17
Server Fable.Elmish - 1.0.3
Server Fable.Elmish.Debugger - 1.0.1
Server Fable.Elmish.HMR - 1.0
Server Fable.Elmish.React - 1.0.3
Server Fable.JsonConverter - 1.0.8
Server FSharp.Core - 4.5.2
Server Fulma - 1.0.0-beta-025
Server Fulma.Extensions - 1.0.0-beta-016
Server jose-jwt - 2.4
Server Saturn - 0.7.4
Performance:
 - Runtime: 604 milliseconds
sashan@deimos sashan/code/titan master ☺ > 
```
I also tried various ways to add it via paket (e.g. .paket/paket.exe add Saturn.Extensions.Authorization -g Server -p src/Server/Server.fsproj)
but they didn't work.

My guess is the Extensions are not in nuget? My paket.dependecies refers to Saturn like this
```
nuget Saturn
```
I'll try and use a github reference and see if that works.

**Comment by Krzysztof-Cieslak** [comment]
`Saturn.Extensions.Authorization` is not yet distributed through NuGet (as there exist couple of things I need to figure out before doing it - https://github.com/SaturnFramework/Saturn/issues/120). I think the simplest way will be using paket github reference to just add https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn.Extensions.Authorization/OAuth.fs).

**Comment by Krzysztof-Cieslak** [comment]
`Saturn.Extensions.Authorization` has been published to NuGet. I will be available when NuGet finishes validation and whatever else it's doing (probably some bitcoin mining) here - https://www.nuget.org/packages/Saturn.Extensions.Authorization/
