### ISSUE TITLE
URLs are case-sensitive

### ISSUE THREAD

**Issue by faabergr** [SaturnFramework/Saturn#145]
I followed the steps in the [How to start in 60 seconds](https://saturnframework.org/docs/guides/how-to-start/) and I noticed that the router URL matching is case sensitive. Casing books with a capital B gets me a 404 error. I'm happy to try to make a PR if someone can point me to the right place in the code. :)

**Comment by talbottmike** [comment]
If you'd like to submit a PR for the docs, the page you are looking for is here.
https://github.com/SaturnFramework/docs/blob/master/docs/guides/how-to-start.md

**Comment by jeremyabbott** [comment]
@faabergr I talked about this with @Krzysztof-Cieslak a couple of weeks ago. We discussed potentially adding a custom operation to Pipelines to convert request paths to lower case. That way it would be opt in. It would effectively prepend an HttpHandler to the pipeline to do something like

```fsharp
ctx.Request.Path <- PathString(ctx.Request.Path.Value.ToLower())
```

**Comment by dustinmoris** [comment]
> It would effectively prepend an HttpHandler to the pipeline to do something like..

You have to be careful though, because if you make the entire path lowercase by default then you might break user input which is embedded in the URL as route arguments. For example a base64 encoded string or a secret string in the route, etc.

**Comment by Krzysztof-Cieslak** [comment]
Potential fix (or rather new feature) in https://github.com/SaturnFramework/Saturn/pull/156
