### ISSUE TITLE
Proper HTML templating

### ISSUE THREAD

**Issue by Immortalin** [SaturnFramework/Saturn#148]
Pure f sharp code makes working with designers etc. _difficult_  Something like Razor pages/ERB would be nice

**Comment by Krzysztof-Cieslak** [comment]
Giraffe supports Razor and dotLiquid templates - https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#additional-features. And as Saturn is built on top of Giraffe, you can easily plug it in - just add NuGet package, and use (for example) `dotLiquid` function in your handlers/controllers.
