### ISSUE TITLE
Needed to explicitly chmod u+x on build.sh

### ISSUE THREAD

**Issue by dsyme** [SaturnFramework/Saturn#15]
title says it all.  On OSX.

```
dotnet new -i Saturn.Template
dotnet new saturn -lang F#
./build.sh
```

--> error

    chmod u+x build.sh

all ok

**Comment by theimowski** [comment]
This is not yet possible within the template engine itself: https://github.com/dotnet/templating/issues/1028

**Comment by Krzysztof-Cieslak** [comment]
Hey, yes as @theimowski said - this is known problem and we can't fix it at the moment. I've added additional information about it to readme (8e1b9bd292afb20e5a459734c9d55fb978442f5f).

@theimowski Do you know if it's possible to display a custom message after creating the project with `dotnet new`?

**Comment by theimowski** [comment]
There are some custom post-actions available https://github.com/dotnet/templating/wiki/Post-Action-Registry but haven't used them yet

**Comment by rmunn** [comment]
@theimowski - Thank you for linking to that issue. I knew I'd researched this at some point last year, and that issue's comments thread is indeed where I posted my results.

BTW, https://github.com/dotnet/templating/pull/1042 contains an example of how to use one of those post-action scripts to run `chmod +x` on any `.sh` files in your template.

**Comment by rmunn** [comment]
I've added documentation about that custom `chmod` post-action to the dotnet templating Wiki, at https://github.com/dotnet/templating/wiki/Post-Action-Registry#change-file-permissions.
