### ISSUE TITLE
Provide IConfiguration as a parameter to use_config

### ISSUE THREAD

**Issue by toburger** [SaturnFramework/Saturn#151]
It would be useful when the `use_config` function of the `application` computation expression provides access to the `Microsoft.Extensions.Configuration.IConfiguration` object or the `HttpContext` itself.

I wanted to read the application settings from ASP.NET Core and put it in a Settings record, but my solution is pretty ugly.

```fsharp
let configureContextAccessor (services: IServiceCollection) =
    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>()

let setupConfiguration () =
    let ctx = HttpContextAccessor()
    let config = ctx.HttpContext.GetService<IConfiguration>()
    { SampleSetting = config.["sampleSetting"] }

let app = application {
	...
	service_config configureContextAccessor
	use_config setupConfiguration
	...
}
```

I couldn't find a nicer way to access the `IConfiguration` object.

**Comment by Krzysztof-Cieslak** [comment]
Yes, currently accessing `IConfiguration` on the application level is a problem. I think I'd be open to changing `use_config` to take `IConfiguration -> 'T` as a parameter, instead of just `'T`

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/SaturnFramework/Saturn/pull/157
