### ISSUE TITLE
DELETE and GET request id is not correct in the controller function

### ISSUE THREAD

**Issue by MarneeDear** [SaturnFramework/Saturn#162]
Possibly related to issue #160 .

DELETE requests to a path with an `id` doesn't parse the `id`.

## For example

DELETE to http://saturn.local:8085/delete/11 
In the controller delete function the `id` is `delete/11`, but it should be `11`

I used Controller.Sample to repro this in a forked branch here:
https://github.com/MarneeDear/Saturn/blob/delete-path-parse/sample/Controller.Sample/Controller.Sample.fs#L82

I suspect this is why I get a 404 when the `id` type is `int` instead of string in issue #160 

## Update

I am seeing the same problem with `getf`. See Controller.Sample in my fork here:

https://github.com/MarneeDear/Saturn/blob/delete-path-parse/sample/Controller.Sample/Controller.Sample.fs#L84

## Other details
Using dotnet on Windows 10
Saturn master branch as of 12/23/2018 at 10pm MDT

**Comment by MarneeDear** [comment]
Can anyone repro this?

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed by #168.
