### ISSUE TITLE
application app_config must provide IHostingEnvironment

### ISSUE THREAD

**Issue by xperiandri** [SaturnFramework/Saturn#163]
How to convert this code into Saturn compliant?
``` F#
if (env.IsDevelopment()) then
    app.UseDeveloperExceptionPage() |> ignore
else
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts() |> ignore
```

**Comment by Krzysztof-Cieslak** [comment]
It's really good question ^_^

**Comment by xperiandri** [comment]
Also `ILogger` created from `ILoggerFactory` would be useful

**Comment by NinoFloris** [comment]
These and other questions at some point pushed me to abandon `application {}` and just use raw webhostbuilder.

However now that panesofglass found an overload trick for custom CE operations we could add all the missing overloads.

**Comment by xperiandri** [comment]
@NinoFloris could you explain or post an excerpt of code?

**Comment by antonburger** [comment]
> 
> 
> @NinoFloris could you explain or post an excerpt of code?

Seems to be referred to here: #164.

with original sources [here](https://github.com/panesofglass/computation-expressions-workshop/blob/master/exercises/08_EDSLs.md#overloading) and [here](https://wizardsofsmart.wordpress.com/2019/01/01/yet-another-f-web-framework/).

I'm still going over the mechanism myself.

**Comment by Krzysztof-Cieslak** [comment]
To answer the original question - this should work fine:

```
app_config (fun app ->
    let env = app.ApplicationServices.GetService<IWebHostEnvironment >()
    if (env.IsDevelopment()) then
        app.UseDeveloperExceptionPage() |> ignore
    else
        // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
        app.UseHsts() |> ignore
```

Saturn 0.14 will include some helper to replace `app.ApplicationServices.GetService<IWebHostEnvironment >()` call with something more user friendly.
