### ISSUE TITLE
Information required: error_handler in Saturn template router CE

### ISSUE THREAD

**Issue by reflash** [SaturnFramework/Saturn#165]
Hi!

I was trying to run Saturn template and create some sample APIs with it.
In the template the commented section contains this apiRouter, which I tried to modify:
```fsharp
let apiRouter = router {
    error_handler (text "Api 404")
    pipe_through api

    get "/hello" (text "Hello")
}
```

It fails with the error_handler function and I don't see it being in any documentation about Router. Is it still relevant code?

**Comment by reflash** [comment]
And also in the same sample it seems plug acceptJson fails all of my requests. I'm not entirely sure about how does it work, so if you could, clarify it, please.

**Comment by vtquan** [comment]
As for the first issue, I encountered the same issue and noticed that `not_found_handler (setStatusCode 404 >=> text "Api 404")` is used in the samples and that is what I have been using instead. Definitely should be updated in the documentation as well.

**Comment by reflash** [comment]
Documentation was updated in the merged PR. Closing the issue
