### ISSUE TITLE
How to use MemoryCache?

### ISSUE THREAD

**Issue by markpattison** [SaturnFramework/Saturn#177]
I can see a reference in the [docs](https://saturnframework.org/docs/api/application/#memory_cache) to an in-memory cache - is this the same as [this one](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)?

If so, I'm struggling to see how to get a reference to it in Saturn.  Is there an example anywhere which shows it being used?

Many thanks!

**Comment by jeremyabbott** [comment]
@markpattison it actually uses the [Distributed Memory Cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-memory-cache).

If you want to use the MemoryCache you referenced, you can wire it up like this:

`service_config (fun s -> s.AddMemoryCache())`

**Comment by markpattison** [comment]
Thank you - unfortunately I'm also struggling to see how to then get a reference to the cache, i.e. the equivalent of the following C# from the docs:

```
public class HomeController : Controller
{
    private IMemoryCache _cache;

    public HomeController(IMemoryCache memoryCache)
    {
        _cache = memoryCache;
    }
}
```

**Comment by jeremyabbott** [comment]
You can get access to the services via the `HttpContext`.

If you have a controller action like this:

```
let indexAction =
        fun (ctx: HttpContext) ->
            task {
                let cache = ctx.GetService<IMemoryCache>()
                let cachedValue = cache.Get("foo") :?> string // or whatever type it is
                return ok ctx cachedValue
            }
            
    let controller = controller {
        index indexAction
    }
```

`GetService<'t>` is an extension on `HttpContext` that's added by `Giraffe` so you'll need to open `Giraffe` before it's available to you.

**Comment by markpattison** [comment]
Got it working, thanks again for the help!
