### ISSUE TITLE
AWS Lambda support

### ISSUE THREAD

**Issue by willsam100** [SaturnFramework/Saturn#178]
Has Saturn been used with AWS Lambda? 

At a high-level, this seems like it should be possible. 
Using Giraffe with AWS' templates creates the following snippet (and more)

```
let configureApp (app : IApplicationBuilder) =
    let env = app.ApplicationServices.GetService<IHostingEnvironment>()
    (match env.IsDevelopment() with
    | true  -> app.UseDeveloperExceptionPage()
    | false -> app.UseGiraffeErrorHandler AppHandlers.errorHandler)
        .UseStaticFiles()
        .UseGiraffe(AppHandlers.webApp) // <----- webApp is an HttpHandler from Giraffe

type LambdaEntryPoint() =
    inherit Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction()

    override this.Init(builder : IWebHostBuilder) =
        let contentRoot = Directory.GetCurrentDirectory()
        
        builder
            .UseContentRoot(contentRoot) 
            .Configure(Action<IApplicationBuilder> configureApp)
            .ConfigureServices(configureServices) // <----- important part
            |> ignore
```

I would guess that a function that can translate the `router` or `application` computation expressions into an HttpHandler would be all that is required. Does this exist?

**Comment by isaacabraham** [comment]
@bruinbrown has been working on this very thing.

**Comment by Krzysztof-Cieslak** [comment]
@isaacabraham Have you've done anything with that in the end?

**Comment by isaacabraham** [comment]
@bruinbrown this was your thing dude :-)

**Comment by bruinbrown** [comment]
@Krzysztof-Cieslak I ended up getting the code changes in place to make it run on lambda but I never got as far as actually invoking that lambda. Then main change that I made was to change the signature of ``ApplicationBuilder`` to take in an optional ``IWebHostBuilder`` which is then provided by the AWS Lambda runtime

**Comment by Rajivhost** [comment]
Hi @bruinbrown, any update?

**Comment by Rajivhost** [comment]
Hi @bruinbrown, any update?

**Comment by DurdSoft** [comment]
I'm also interested in this. It seems, perhaps naively on my behalf, that we should be able to pass in an instance of `IWebHostBuilder` to be used [here](https://github.com/SaturnFramework/Saturn/blob/0d77d17c99214612166983f92de8bf08e01dab04/src/Saturn/Application.fs#L92). 

We would then need an `IWebHostBuilder option` on `ApplicationState` and a custom operation `use_builder` (or similar) to add it to the state. 

I may have a look into this today and see what I come up with...

**Comment by cartermp** [comment]
I'll close this out, since there's a standard way to do this that fits within the idioms of AWS Lambda.

I'm hesitant to add docs or a template here, since platforms like Lambda tend to be moving targets that change their model for how things work every year or so (at least that was my experience with Azure Functions).
