### ISSUE TITLE
Why is required mono on Mac?

### ISSUE THREAD

**Issue by chespinoza** [SaturnFramework/Saturn#189]
Hi, a noob question.. why `Saturn` requires `mono` on Mac? I built successfully a testing `Suave` web app without installing it, and not happy to install mono really as can develop and build stuff just with `dotnet` :face_with_rolling_eyes: (edited) 

and btw Giraffe also builds & run without `mono` :confused:

**Comment by Krzysztof-Cieslak** [comment]
It's (current, it will be changed Soon ™️)  requirement of Paket, that is used by us in `dotnet new saturn` template.
