### ISSUE TITLE
Q: split functionality to smaller package

### ISSUE THREAD

**Issue by stijnmoreels** [SaturnFramework/Saturn#195]
Question:

The Saturn project itself consists of a lot of functionality and only some extra functionality is split in separate packages.
It seems reasonable to also split some more into diff categories since if you now would use Saturn to build only a REST API; you end up with a lot of packages  not always related to your cause.

(ASP.NET Cookies, session, static files, ...)

**Comment by Krzysztof-Cieslak** [comment]
Given how ASP.Net Core 3 is supposed to be used (`FrameworkRefrences`) I don't think it makes sense to split Saturn more than it's split right now.
