### ISSUE TITLE
`Response.accepted` fails to serialize response

### ISSUE THREAD

**Issue by et1975** [SaturnFramework/Saturn#197]
Getting
>System.ArgumentException: Could not determine JSON object type for type Microsoft.FSharp.Collections.FSharpList`1[Presentation+Link].
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Thoth.Json.Net.Encode.autoEncoder@513-14.Invoke(Object v)
   at Thoth.Json.Giraffe.ThothSerializer.Giraffe-Serialization-Json-IJsonSerializer-SerializeToBytes[T](T o)
   at Giraffe.ResponseWriters.HttpContext.WriteJsonAsync[T](HttpContext this, T dataObj) in C:\projects\giraffe\src\Giraffe\ResponseWriters.fs:line 137

`json` function and `ctx.WriteJsonAsync` has no problem serializing `Presentation.Link list` type elsewhere. What am I doing wrong?

here's how I'm calling it:
```fsharp
let somePost : HttpHandler =
    fun _ ctx ->
        task {
            return! 
                { id = id
                  links = mkLinks id }
                |> Response.accepted ctx
        }
```
and the router:
```fsharp
let router = router {
    post "/" somePost
}
```

**Comment by et1975** [comment]
Added unit tests that roundtrip these types using Thoth's `IJsonSerializer` impl and they pass. Looking for ideas...

**Comment by MangelMaxime** [comment]
Do you what `Response.accepted` is calling for serializing the JSON?

Implement seems to be, but I don't know it's being handled by Saturn or Giraffe.

```fs
    let accepted (ctx: HttpContext) res =
      Successful.ACCEPTED res Common.halt ctx
```

**Comment by et1975** [comment]
Looking at the stack trace `ACCEPTED` calls `ctx.WriteJsonAsync`, but if I call `ctx.WriteJsonAsync` directly it serializes successfuly!

**Comment by ChrSteinert** [comment]
Do you also use the `SerializeToBytes` function in your tests?

**Comment by MangelMaxime** [comment]
@ChrSteinert Is the question for me?

**Comment by ChrSteinert** [comment]
Sorry, @MangelMaxime - the question was for @et1975

**Comment by et1975** [comment]
> Do you also use the `SerializeToBytes` function in your tests?

@ChrSteinert no.

**Comment by Krzysztof-Cieslak** [comment]
Hey, I can't reproduce that on current master, this test is passing just fine - https://github.com/SaturnFramework/Saturn/blob/master/tests/Saturn.UnitTests/SimpleTests.fs

**Comment by et1975** [comment]
Let's close this, I'm not working anymore on the project where this came up.
