### ISSUE TITLE
Add helpers for other authentication methods

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/Saturn#20]

**Comment by Nhowka** [comment]
This includes the definition of roles for using with `requires_role`?

**Comment by Krzysztof-Cieslak** [comment]
Hey, yes - I've added helpers for requiring role, or claim in authentication refactoring I've done today. 

The helpers that can be plugged in `scope`, `pipeline` or `controller` are here - https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Authentication.fs

The helpers for `application`  - https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Application.fs#L157-L235

Feedback welcomed.

**Comment by Nhowka** [comment]
Not really the helper I had in mind, but something for that part: https://vtquan.github.io/fsharp/setting-up-services-with-giraffe/

**Comment by Krzysztof-Cieslak** [comment]
Oooh.. sure, adding those should be possible!

**Comment by Nhowka** [comment]
There is a lot that can be added to `IServiceCollection` and not sure where the line should be drawn. Maybe just having a helper to add a custom service to `ServicesConfig` would be enough in the case where the user need it.

**Comment by Krzysztof-Cieslak** [comment]
Helper for adding custom `ServiceConfig` configuration definitely should be there - I'm not sure why it's not here since I've added similar helpers for both `ApplicationBuilder` and `WebHostBuilder - https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Application.fs#L77-L85

And looking again at the link you've provided - how does `AddAuthorization` fits with non-MVC applications (i.e. Giraffe)? MSFT documentation essentially points to using `[<Authorize>]` attributes on MVC controllers which is not the case for us.

**Comment by Nhowka** [comment]
I was probably assuming stuff that is not true. I was understanding that these policies could behave as a role alias so I could use them in `requires_role`. Like the link, using `Administrators` to match Administrator and `Moderators` to match Administrator or Moderator.

Could we have a `requires_policy` with that behaviour?

**Comment by Krzysztof-Cieslak** [comment]
Authentication helpers implemented in 3fe92abda0fce83890595b84574f3d028cc4974e

Authorization helpers discussion moved to #26
