### ISSUE TITLE
How to connect to a channel?

### ISSUE THREAD

**Issue by mastoj** [SaturnFramework/Saturn#200]
There is no sample on connecting to a channel and I struggle. I thought it would just be to send som data that looks like:

```
{
    "Topic": "the-topic",
    "Payload": { ... payload ... }
}
```

But my handler won't trigger. I do see that I manage to join.

**Comment by huwmanatee** [comment]
I had the same trouble, You're also missing a Ref: string field. 
Also depending on whether you're using the default serializer or not yoy might need to check the casing of the members.

**Comment by Krzysztof-Cieslak** [comment]
Sorry, for lack of the documentations - channels are still bit experimental, so I don't want to push into people them too hard at the moment. 

As @huwmanatee mentioned, it seems the problem here is missing `Ref` field.

**Comment by mastoj** [comment]
No need to excuse yourself. I can maybe push some docs up if I ever get the
time to play with it again.

**Comment by mastoj** [comment]
What does the ref field do? I still struggle to get it working. Is there a good example of a fable client somewhere I can look at?

**Comment by sgoguen** [comment]
I was able to trigger the handler in the JavaScript console with the following:

```javascript
var exampleSocket = new WebSocket("ws://localhost:8085/channel");
exampleSocket.send(JSON.stringify({ Topic: 'topic', Ref: 1, Payload: 'Test' }));
```

**Comment by robertpi** [comment]
There's an example of using channels here as well: https://github.com/CompositionalIT/safe-sockets

**Comment by Krzysztof-Cieslak** [comment]
Ok, given there are some examples linked above that are working, I'll close this issue. Obviously, we still miss documentation on the topic, but hopefully, we'll be able to solve it given that I've modernized all the infrastructure about Saturn documentation.
