### ISSUE TITLE
cannot get grpc extension to work in own project

### ISSUE THREAD

**Issue by dgrimmin** [SaturnFramework/Saturn#204]
Let me start by saying the grpc extension is a really valuable addition to the Saturn framework, which is itself a pleasure to work with.

I get the grpc sample to work when I clone the gitrepo. It even nicely supports seq(float) that I require. It is so cool you only need to annotate the shared types to get grpc to work.

However, when I want to incorporate the saturn grpc extension in my project I get an error:

`"[...]Application startup exception: System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)[...]"
`

Which I recon is a versioning thing according to https://github.com/grpc/grpc-dotnet/issues/246 .

This happens when I take the grpc example content and I reference Saturn and Saturn.Extensions.grpc. All is well according to intellisense (datatype-wise), but during runtime I get the above crash.

Any suggestions on how to manage the (transitive) package versions would be much appreciated. I am targetting netcoreapp3.0 as it seems to be a minimum requirement for grpc.

**Comment by isaacabraham** [comment]
Are you using NuGet or Paket? And yes GRPC is netcore3.x and above only.

**Comment by dgrimmin** [comment]
Paket, so I have been diving into the paket.lock file until my head was spinning. I am really hoping for some high levels settings to magically appear as a possible solution.

**Comment by isaacabraham** [comment]
Could you post the lock file (and / or a basic repro repository?). Thanks!

**Comment by dgrimmin** [comment]
Yes, later this evening as I am not in front of my computer. What I found weird several times is that after adding the extension there are also complaints about netstandard2.1 versions requested but not available, and lots of dependencies with a >= 2.x that seem to sometimes result in 3.0 versions being found.

**Comment by dgrimmin** [comment]
Hi Isaac,

Thank you for wanting to help.

I tried setting up a new minimal example here: https://github.com/dgrimmin/saturn.grpc.git . Somehow I could not manage to get the .paket directory in there, but this is a start. Already here after adding saturn.extensions.grpc and doing a "fake build" I get issues:

`There was a problem while setting up the environment:
-> Error during parsing of 'C:\Users\d.grimminck\SaturnGithub\paket.lock'.
-> failed to parse line '      Grpc.Core.Api (>= 2.23) - restriction: >= netstandard2.1' (invalid parameter 'netstandard2.1' after >= or < in '>= netstandard2.1') (Could not parse 'framework: restriction: >= netstandard2.1' as key/value pairs.)
        -  invalid parameter 'netstandard2.1' after >= or < in '>= netstandard2.1'`

Earlier today I more or less fixed this problem by replacing the netstandard2.1 with netstandard2.0, but I must have done it slightly different then, since now that just gives me another warning:

`Script reported an error:
-> TypeInitializationException: The type initializer for '<StartupCode$Fake-Core-Target>.$Target' threw an exception.
-> MissingMethodException: Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<!!0[]> Microsoft.FSharp.Control.FSharpAsync.Parallel(System.Collections.Generic.IEnumerable`1<Microsoft.FSharp.Control.FSharpAsync`1<!!0>>, Microsoft.FSharp.Core.FSharpOption`1<Int32>)'.`

Part of the paket.lock file of the project I was working on I put in the paket_ownproject.lock file in the same repo. With this lock file I managed to get eventually to a successful compilation, but a crash at runtime.

Hope this is helping...

**Comment by dgrimmin** [comment]
Hi Isaac,

Thank you for wanting to help.

Here I created a minimal example https://github.com/dgrimmin/saturn-grpc-issue .
>fake build
>dotnet .\src\gRpcSample\bin\Release\netcoreapp3.0\gRpcSample.dll

`Application startup exception: System.MissingMethodException: Method not found: Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder).
   at Saturn.configureGrpcEndpoint@21-1.Invoke(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action1 configure)
   at Saturn.configureGrpcEndpoint@21.Invoke(IApplicationBuilder app)`

I hope you are able to help.

**Comment by isaacabraham** [comment]
@dgrimmin I can repro here (I killed the lockfile and recreated just in case). Can you compare with this: https://github.com/protobuf-net/protobuf-net.Grpc/tree/master/examples/pb-net-grpc (which doesn't use saturn) - what's the difference? Perhaps convert the F# packages here with Paket and see what changes.

**Comment by slang25** [comment]
I think referencing Giraffe 4 will fix this, related: https://github.com/SaturnFramework/Saturn/issues/201

**Comment by isaacabraham** [comment]
@slang25 could be. I'd love to better understand why it's happening nonetheless.

**Comment by slang25** [comment]
Actually it's a little different to what I thought.
It is expecting the return type on `MapGrpcService` to be different from what's in v2.23.2 :
https://github.com/grpc/grpc-dotnet/blob/v2.23.2/src/Grpc.AspNetCore.Server/GrpcEndpointRouteBuilderExtensions.cs#L39

`Saturn.Extensions.gRPC` has been compiled against a lower version which is not binary compatible. This could be fixed by lower the `protobuf-net.Grpc.AspNetCore` in Saturn, or rebuilding with a newer minimum.

**Comment by dgrimmin** [comment]
Thank you for the insights. This is in line with the feeling I got when diving into the paket.lock files of the saturn repo and my own project.

I really hope this will provide the fix for the grpc extension. I’d love to start using it in production.

**Comment by isaacabraham** [comment]
@slang25 right. Do you know which version of the nuget package uses the "correct" (i.e. old!) version? That way at least @dgrimmin could be unblocked in the immediate term.

**Comment by dgrimmin** [comment]
@slang25, what is keeping you from answering Isaac’s? Anything I can do to help?

**Comment by slang25** [comment]
@dgrimmin I tried but failed to figure out the right combination of package versions. I'll try again and let you know how I get on. What I first tried logically should have worked, so I'm missing something here.

**Comment by dgrimmin** [comment]
@slang25, your effort is much appreciated! If there are checks I can perform, please let me know.

**Comment by Krzysztof-Cieslak** [comment]
I think this should be solved with Giraffe 4.X and Saturn targeting `netcoreapp3.1`
