### ISSUE TITLE
Doc Issue in Getting Started

### ISSUE THREAD

**Issue by melston** [SaturnFramework/Saturn#212]
I had problems with the getting started page as just following the steps left me with a bunch of errors.  I had to completely delete the project and start over.  The problem is that the 'global.json' file in the root directory comes pre-loaded with a version of the sdk I didn't have installed and I was unaware I needed to change this.  Once I figured it out I couldn't just change it and continue on as there were, apparently, a lot of config files that had been created that I needed to clean up.  The simplest way to deal with the issue was to just start over and put in my installed sdk version (3.0.100).

**Comment by ChrSteinert** [comment]
@Krzysztof-Cieslak  – can be closed, no?
