### ISSUE TITLE
Remove dependency on Microsoft.AspNetCore package

### ISSUE THREAD

**Issue by theimowski** [SaturnFramework/Saturn#214]
This is related to https://github.com/SAFE-Stack/SAFE-template/issues/326

Don't know the details but the `Microsoft.AspNetCore` package seems to be "obsolete"/"not meant to be used anymore" (It's been last updated 03.12.2018, while e.g. `Microsoft.AspNetCore.App` on 2 months ago)

For some reason having this package as a dependency makes the webapp fail in Azure AppEngine environment

**Comment by baronfel** [comment]
Here's a good example: https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus.AspNetCore/Prometheus.AspNetCore.csproj

note the conditional dependency on a frameworkreference to aspnetcore instead of the packagereference

**Comment by baronfel** [comment]
This should be closed now with #215 having been merged and released.

**Comment by theimowski** [comment]
Yup, fixed in 0.11 - thanks a lot!
