### ISSUE TITLE
Issues with netcore3.0/1 clean project

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#216]
There are some incompatibilities with Paket, Saturn and combinations of netcore30 and 31.

## Defaults

1. Create a new console app with netcore31 sdk (LTS) e.g. `dotnet new console -lang f#`.
2. Create a new paket file using `paket init`.
3. Add Saturn e.g. `paket add saturn -p myapp`.
4. Start the app `dotnet run`.

You get the following error:

```
Unhandled exception.
   Cannot print exception string because Exception.ToString() failed.
```

## 2. Try downgrading the project
1. Amend `myapp.fsproj` to netcore30

```xml
    <TargetFramework>netcoreapp3.0</TargetFramework>
```

2. `paket install`
3. `dotnet run`

```
error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 3.1.1 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 3.1.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

The build failed. Fix the build errors and run again.
```

You can fix it by upgrading the paket file to netcore31 instead of downgrading the project. However, the default combinations don't work.

tagging @forki @baronfel @Krzysztof-Cieslak

**Comment by forki** [comment]
It should be fixed by making Paket emit Netcoreapp3.1

Isaac Abraham <notifications@github.com> schrieb am So., 2. Feb. 2020,
16:41:

**Comment by baronfel** [comment]
So this is just the paket init default file specifying a TFM of netcoreapp3.1? Can that be worked around by making paket assume framework: auto?

**Comment by isaacabraham** [comment]
I'll submit a PR to update Paket, although I don't fully understand what these errors are caused by. It's so confusing.

**Comment by isaacabraham** [comment]
I've created a basic PR, this'll be fixed next week.

**Comment by isaacabraham** [comment]
This is fixed in the latest Paket.
