### ISSUE TITLE
Remove Microsoft.AspNetCore.Authorization.OAuth for netcore3x?

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#217]
My (limited) understanding is that this is now a framework reference and so perhaps isn't required as a nuget package?

**Comment by isaacabraham** [comment]
See this https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#add-package-references-for-removed-assemblies

**Comment by baronfel** [comment]
Good catch, it should be removed in the 3.x line 👍

**Comment by isaacabraham** [comment]
I've created an experimental repo to highlight the reductions that are possible:

1. Removing Authorization and Auth packages: https://github.com/CompositionalIT/saturn-deps/commit/f8be21a30a066af625bb25362b4fe103e4b513e2
2. Once Giraffe 3 is released (and if we accept TaskBuilder 2.2 alpha): https://github.com/CompositionalIT/saturn-deps/commit/6acf0025bc1a392fed9a0d236f29d47d801179c2.

This will leave us with a 64 line paket lock file, down from 307 lines.
