### ISSUE TITLE
netcoreapp3.1 support?

### ISSUE THREAD

**Issue by baronfel** [SaturnFramework/Saturn#218]
Should we create another packaging target for netcoreapp3.1 support?

**Comment by isaacabraham** [comment]
Given that 3.1 is LTS that might be a good idea. I think it's unfortunate that netcore3.0 came out and wasn't LTS.

**Comment by BlooDCrescent** [comment]
Having netcore3.1 would be awesome!

**Comment by aeshthetic** [comment]
How difficult would this be to implement? What steps would need to be taken?

**Comment by baronfel** [comment]
I've got it going in https://github.com/SaturnFramework/Saturn/pull/220

**Comment by Krzysztof-Cieslak** [comment]
Released in `0.12.0`
