### ISSUE TITLE
Saturn.Extensions.Authorization broken in release 0.11.0

### ISSUE THREAD

**Issue by rusanov-vladimir** [SaturnFramework/Saturn#221]
After upgrading to the version 0.11.0 the use of `use_github_oauth` in `application` CE leads to cryptic:
`This control construct may only be used if the computation expression builder defines a 'For' method`

It appears that it's caused by name collision with `Microsoft.AspNetCore.Builder.ApplicationBuilder` in OAuth extensions.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.12.0`
