### ISSUE TITLE
Discussion: should channel handles have socketId as a parameter?

### ISSUE THREAD

**Issue by robertpi** [SaturnFramework/Saturn#226]
In some cases I'd like to be able to send a reply message just to the channel that sent it. Currently the handle does not take the socketId as a parameter, so this is quite difficult.

You can store the socketId when the user connects so be able to talk to the channels that are associated with a user, but since a user could open several pages and therefore several connections, you have do way to know which of the users connections send the original messages.

**Comment by robertpi** [comment]
I would say the same for terminate. Seems there's no easy way to know which socket is closing.

(Although I could be missing something obvious)

**Comment by robertpi** [comment]
Suggested a possible implementation in this PR: https://github.com/SaturnFramework/Saturn/pull/227

**Comment by Krzysztof-Cieslak** [comment]
I've actually thought I've added it to handle 😅

**Comment by robertpi** [comment]
I definitely need access to the socket id in both handle and terminate, so we need to decide whether this merits a breaking change or not.

**Comment by Krzysztof-Cieslak** [comment]
Oh, yes, Saturn is still before 1.0, so breaking changes are somehow expected from time to time.

**Comment by Krzysztof-Cieslak** [comment]
Ok, this got merged, it will be released in next version of Saturn.
