### ISSUE TITLE
Suggestion about docs - API Link 

### ISSUE THREAD

**Issue by MecuSorin** [SaturnFramework/Saturn#231]
I think that the API reference link should directly go to https://saturnframework.org///reference/Saturn.html instead of https://saturnframework.org///reference/api-ref.html

**Comment by Krzysztof-Cieslak** [comment]
This got reworked a bit in https://github.com/SaturnFramework/Saturn/commit/9e67fe1a118a5569a47f14e6f4adb3317a681b53. Now API References tab list all separate projects we release (Saturn and Extensions). Each project still has "index" page - while, it's not the case right now, we could expose multiple namespaces from single project.
