### ISSUE TITLE
Move OpenId Auth into the Authorization namespace

### ISSUE THREAD

**Issue by ChrSteinert** [SaturnFramework/Saturn#234]
While browsing the new and cool documentation I realized, that there is `Saturn.Extensions.Authorization` with members like `use_google_oauth_with_config` and `Saturn.Extensions.OpenIdConnect` with its only members `use_open_id_auth_with_config`.

I thought, maybe it would make sense to move the OpenIdConnect member over to `Authorization` as well? I know this would be a breaking change, but seems like it makes sense. The old member could forward to the new one and be marked with `[<Obsoleted>]` for a few releases?

**Comment by Krzysztof-Cieslak** [comment]
Yeah, sounds like a good idea.

**Comment by ChrSteinert** [comment]
Let me PR it ;)
