### ISSUE TITLE
Deprecating netstandard2.0

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/Saturn#237]
I'm planning to remove multi-targeting into `netstandard2.0`. It just complicates build/dependency/packaging story without huge advantage - full framework .Net is not really something we should support (especially given the Saturn is mostly used for greenfield projects, I'd assume), and supporting older .Net Core versions is also bit unnecessary - as far as I know .Net Core 3.X adaption rates are really good.

**Comment by johlrich** [comment]
Just a heads up: a group affected would be folks hosting on Azure Functions v2 runtime (`netcoreapp2.2` underneath). 

My company does have a few apps there, but tbh I don't mind those being version locked until I get them updated and tested against v3.

**Comment by Krzysztof-Cieslak** [comment]
Also, it’s not like I’m planning to do right away - there will be still few versions that will support netstandard2.0, maybe we’ll add some depreciation warning. 

And well, that’s why I’ve created this issue- to suggest to users to slowly move towards 3.X

**Comment by Krzysztof-Cieslak** [comment]
I'm slowly starting to work on `0.14.X` version of Saturn and it will not support `netstandard2.0` any more.

**Comment by Krzysztof-Cieslak** [comment]
Implemented in #257
