### ISSUE TITLE
Non-code configuration

### ISSUE THREAD

**Issue by alfonsogarciacaro** [SaturnFramework/Saturn#24]
I couldn't find anything in the post/README/samples yet, is there any idea about how to handle configuration with an external file (like a JSON)? This can be useful to have different configurations according to the environment and maybe even make some changes on the fly. Using ASP.NET Core JSON configuration has some benefits as expressed in this comment: https://github.com/SAFE-Stack/SAFE-BookStore/pull/255#issuecomment-352172785

**Comment by Krzysztof-Cieslak** [comment]
I still haven't really figured out configuration. I like many things that ASP.NET Core is doing (different providers, detecting changes etc.) so maybe I will try to use just their stuff and work around the fact they use DI framework...

**Comment by alfonsogarciacaro** [comment]
Sorry, I just noticed I pasted the wrong link above, I just fixed it ☝️ 

Please note here I'm talking about configuration you usually put in an external file, like log level, connection strings, etc. In the (fixed) link above Vasily says ASP.NET Core Configuration bypasses IIS caching so it's good for changes on-the-fly.

**Comment by Krzysztof-Cieslak** [comment]
Configuration should be handled by built-in ASP.NET Core way of handling config.
