### ISSUE TITLE
support for IHostBuilder configuration missing.

### ISSUE THREAD

**Issue by vilinski** [SaturnFramework/Saturn#246]
Please correct me if I'm wrong. Seems that saturn is IWebHostBuilder centric. Since .NET 3.1 there is a generic host interface IHostBuilder to use instead. So there is no possibility to access the IHostBuilder interface in Saturn?
An example where it would be already useful is the Orleans 3.0 co-hosting in one process together with a web application. The `UseOrleans(this IHostBuilder)` extension method is defined for `IHostBuilder` rather than `IWebHostBuilder` where the most part of other web-related configuration is kept.
I thouthg first to come with a PR, adding additional `host_config` overload, but failed to make it compilable.

Or may be I miss an obvious way around saturn how this could be easily accomplished?

**Comment by Krzysztof-Cieslak** [comment]
Implemented as part of #257
