### ISSUE TITLE
DBUP option instead of fluent migrations

### ISSUE THREAD

**Issue by jkone27** [SaturnFramework/Saturn#250]
I believe for DB migrations , giving also the simpler **DbUp** (using sql scripts) as option would be really nice, instead of migration DSL packages like fluent-migrator. But this is indeed more for Saturn repo, will post it there.

https://dbup.readthedocs.io/en/latest/philosophy-behind-dbup/

also combining **Fsharp.Data.SqlClient** might make migration sql scripts compile-time checked :)

**Comment by Krzysztof-Cieslak** [comment]
>  instead of migration DSL packages like fluent-migrator. 

Saturn is not using any migration DSLs. Actually Saturn itself is not using any migrations - we have support for some in the template and CLI tool. In this case, we're using Simple.Migrations which are using normal SQL for migrations, and I'm really happy with it, so we won't make any changes here just for sake of making changes. 

Thanks for the suggestion!

**Comment by jkone27** [comment]
well it does not use sql scripts, does it? i mean file with .sql extension,
it uses SQL but as a string, though could also be compiled checked there with Fsharp.Data.SqlClient as well. Ok, thanks
