### ISSUE TITLE
Templates for Visual Studio

### ISSUE THREAD

**Issue by xperiandri** [SaturnFramework/Saturn#27]
What about templates for Visual Studio?

**Comment by Krzysztof-Cieslak** [comment]
I know nothing about templating in VS, if someone would provide template, I'd be happy to put it in `SaturnFramework` org. But it's not something I'll be working on.

**Comment by isaacabraham** [comment]
There's the `dotnet` template which (to me) seems like the way to go forward anyway.

**Comment by Krzysztof-Cieslak** [comment]
Personally for me yes, `dotnet` template is a way forward. But as I said - if someone wants to work on VS template than I'll be happy to host it in Saturn org.

**Comment by voronoipotato** [comment]
a VS template is not a bad idea, there are entire workplaces that turn their nose at anything but Visual Studio, yes even visual studio code. I don't really have words.

**Comment by Krzysztof-Cieslak** [comment]
I'm not planning to provide any specific VS templates. `dotnet new` templates are main way to create applications in .Net nowadays, anyway.
