### ISSUE TITLE
Microsft.AspNetCore.Authentication.JwtBearer not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by debuginfo** [SaturnFramework/Saturn#279]
Having issues with trying to upgrade Saturn to 0.14.1 in a .NET Core 3.1 app.

Error NU1202	Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0 is not compatible with netcoreapp3.1 1	

Is this a known issue at all?

**Comment by baronfel** [comment]
You've somehow floated the version of Microsoft.AspNetCore.Authentication.JwtBearer past whaat Saturn 0.14.1 supports. You should constrain that package back down, as Saturn 0.14.1 (per the [nuget page](https://www.nuget.org/packages/Saturn/0.14.1)) supports from 3.0.3 and up.  Alternatively, if you want to try .net 5, saturn has a 0.15 prerelease that brings support for aspnetcore in .net 5.

**Comment by debuginfo** [comment]
Ah! You're right! I've just quickly spun up a Hello SaturnSample and it's targeting JwtBearer 3.1.5. I've constrained it down and it's pulling it in correctly.

** Closing as no issue.
