### ISSUE TITLE
Scaffolding support in for Visual Studio

### ISSUE THREAD

**Issue by xperiandri** [SaturnFramework/Saturn#28]
What about scaffolding support in for Visual Studio

**Comment by Krzysztof-Cieslak** [comment]
I believe it would require VS extension, and I'm not planning to work on VS extension. Just like with other issue - happy to include it in `SaturnFramework` organization if sometimes wants to do it, but personally I won't.

**Comment by Krzysztof-Cieslak** [comment]
As with other issue - using per-repo tools is now one of the standard ways of development in .Net Core, not planning to do anything VS specific.
