### ISSUE TITLE
Giraffe latest preview: IXmlSerializer is now Xml.ISerializer

### ISSUE THREAD

**Issue by theimowski** [SaturnFramework/Saturn#281]
[Giraffe 5.0-rc3](https://github.com/giraffe-fsharp/Giraffe/blob/master/RELEASE_NOTES.md#500-rc-3) introduces a breaking change: `IXmlSerializer is now Xml.ISerializer`
When trying to compile Saturn 0.15.0-preview01 with Giraffe 5.0-rc6 following error occurs:
```
FSC : error FS0193: The module/namespace 'Giraffe.Serialization.Xml' from compilation unit 'Giraffe' did not contain the namespace, module or type 'IXmlSerializer' 
```

**Comment by theimowski** [comment]
Tried to give it a go, but that's not as simple - Giraffe 5.0-rc3 supports only `net50`, so that's quite a big change

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed in the latest Saturn preview.

**Comment by vilinski** [comment]
trying to upgrade a project's Giraffe to 5.0.0. Getting the [same compile error ](https://github.com/SaturnFramework/Saturn/issues/281#issue-761639949)
