### ISSUE TITLE
invalid parameter 'net50' after >= or < in '== net50' while upgrading Saturn from netcoreapp3.1 to net5.0

### ISSUE THREAD

**Issue by imranypatel** [SaturnFramework/Saturn#284]
### Description

Error while targetting net5.0 framework.

### Repro steps

1. dotnet new -i Saturn.Template
2. md saturn2net5
3. dotnet new saturn -lang F#
4. Change TFM in saturn2net5.fsproj TargetFramework as: net5.0
5. Change TFM in paket.dependencies as: framework: net5.0
6. dotnet new tool-manifest --force
7. dotnet tool install paket
8. dotnet tool install fake-cli
9. dotnet tool install saturn.cli
10. dotnet paket update
11. dotnet fake build -t run

### Expected behavior

Build and run project successfully on net5.0

### Actual behavior

Producing error:
> There was a problem while setting up the environment:
> -> Error during parsing of 'D:\Work\iprnd\fs\ipstackNG21\saturn2net5\paket.lock'.
> -> invalid parameter 'net50' after >= or < in '== net50'
> Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.

### Known workarounds

Still searching...

### Related information 

* Operating system Windows 10
*  Version of .Net Core
> .NET SDK (reflecting any global.json):
>  Version:   5.0.101
>  Commit:    d05174dc5a
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19041
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

* Version of Paket (5.257.0)
* Version of FAKE-CLI (5.20.3)
* Version of SATURN.CLI (0.12.1)
* Version of F#
> D:\Work\iprnd\fs\ipstackNG21\saturn2net5>dotnet fsi
> Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0

**Comment by noklesta** [comment]
I think you need a prerelease version of paket. I am successfully using paket 6.0.0-beta8 with net5.0.

**Comment by Krzysztof-Cieslak** [comment]
Yes, you need to use preview version of paket for .net5.0 support.
