### ISSUE TITLE
Stable 0.15.0 Release?

### ISSUE THREAD

**Issue by rastreus** [SaturnFramework/Saturn#307]
Giraffe created a stable release for Giraffe 5 ([https://github.com/giraffe-fsharp/Giraffe/releases/tag/v5.0.0](https://github.com/giraffe-fsharp/Giraffe/releases/tag/v5.0.0)).

Will there be more prerelease 0.15.0-preview versions for testing?

If not, will a PR for a stable 0.15.0 release be accepted?

**Comment by forki** [comment]
@Krzysztof-Cieslak told me it's coming very soon.

**Comment by rastreus** [comment]
Thank you for letting me know, @forki, and thank you for all your hard work on Saturn, @Krzysztof-Cieslak.
