### ISSUE TITLE
Build warning on minimal example

### ISSUE THREAD

**Issue by markpattison** [SaturnFramework/Saturn#308]
I'm using the latest .NET SDK (5.0.301)
Following the "Hello World [example](https://saturnframework.org/tutorials/how-to-start.html), if I do the following:

```
dotnet new console -lang F#
dotnet add package Saturn
dotnet restore
```

I get the following warning:

```
C:\Repos\test\test.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 5.0.1 to 5.0.0. Reference the package directly from the project to select a different version.                                                                                                                                                                 nt version. 
C:\Repos\test\test.fsproj : warning NU1605:  test -> Saturn 0.15.0 -> FSharp.Core (>= 5.0.1)
C:\Repos\test\test.fsproj : warning NU1605:  test -> FSharp.Core (>= 5.0.0)
```

The `FSharp.Core` package can't be added directly to the project using the `dotnet add package` (an error `Cannot edit items in imported files` is shown), and adding it manually doesn't change the warning.

Is this an issue with Saturn, or one for the dotnet/F# teams?

**Comment by Zaid-Ajaj** [comment]
Using latest dotnet sdk v5.x means that F# projects _implicitly_ require FSharp.Core v5.0.0 but since Saturn uses latest v5.0.1 you have to explicitly say the project needs v5.0.1
```xml
<PackageReference Update="FSharp.Core" Version="5.0.1" />
``` 
That said, does Saturn actually need v5.0.1 of FSharp.Core? if a downgrade is possible, it would be nicer for beginners to not encounter these kinds of issues

**Comment by markpattison** [comment]
Thanks, I wasn't aware of the `Update` rather than `Include` syntax.  Can't find any docs on it either!
