### ISSUE TITLE
Adding a new controller - View expected string but got xml node

### ISSUE THREAD

**Issue by supertom44** [SaturnFramework/Saturn#31]
When following along with the quick start and adding a new controller using tool, I get the following compile error:

`D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(16,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(16,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(27,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(27,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(29,39): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(35,28): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(35,28): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(43,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(43,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(45,39): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(64,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(64,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(80,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]
D:\Projects\ToRead\src\ToRead\Books\BooksController.fs(80,40): error FS0001: This expression was expected to have type    'string'    but here has type    'Giraffe.GiraffeViewEngine.XmlNode' [D:\Projects\ToRead\src\ToRead\ToRead.fsproj]

Build FAILED.`
![compileerror](https://user-images.githubusercontent.com/6057877/36681207-e5b254f4-1b0f-11e8-9155-0ecf07880aa2.png)

**Comment by mtnrbq** [comment]
I had the same issue and worked around it by adding a new function
```fsharp
  let asString (xml:GiraffeViewEngine.XmlNode) = 
                  Giraffe.GiraffeViewEngine.renderXmlNode xml
```
and then adding it into the generated code:
```fsharp
return! Controller.render ctx (asString (Views.index ctx (List.ofSeq result)))
```

Ideally I think it should be added to `ControllerHelpers.fs`
```fsharp
    ///Returns to the client rendered template.
    let renderXml (ctx: HttpContext) template =
      ctx.WriteHtmlStringAsync (Giraffe.GiraffeViewEngine.renderXmlNode template)

```
And then update the template to call it:
```fsharp
return! Controller.renderXml ctx  (Views.index ctx (List.ofSeq result))
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in latest release
