### ISSUE TITLE
When should we update the project to .NET 6?

### ISSUE THREAD

**Issue by 64J0** [SaturnFramework/Saturn#321]
I'm relatively new in this .NET world and don't know when it is good to migrate a project from a past version to the next one (.NET 5 -> .NET 6). How do you guys decide this?

**Comment by cartermp** [comment]
TL;DR it'll be a few more weeks (a month maybe?) before you can do this

Work to update is here: https://github.com/SaturnFramework/Saturn/pull/322

There is a _truly_ upstream issue in the F# compiler that has a fix, but that fix is not released yet. When that propagates down, Giraffe can update and no longer be a preview. We can update things concurrently here, but I wouldn't want to have a non-preview of Saturn published if the upstream Giraffe dependency is also a preview. So there's a chain of work here sourced all the way at the compiler and the Microsoft release process!

**Comment by 64J0** [comment]
Apparently, it is updated now, right?

Considering this PR: https://github.com/SaturnFramework/Saturn/pull/322.

**Comment by Krzysztof-Cieslak** [comment]
Yes, indeed.
