### ISSUE TITLE
Feature Request for wider adaptation

### ISSUE THREAD

**Issue by davidjeba** [SaturnFramework/Saturn#324]
Saturn is an unknown framework so far.
as its in F# i dont know where to start.
also i have a lots of why, should i? use this framework

maybe its good for freelancers who has enough time to learn something new.
but majority of the developers love bootstrap templates, a starter kit etc
so, using that they can immediately jump in and learn f# on their way...

1. tailwindui.com - best place to kickstart something on tailwind.
Q: Can we have something like fsharptemplates.com which developers can use 

2. framework7.io - gives so much of flexible platform of choice to the developers
Framework7 Core / API
Framework7 Vue
Framework7 React
Framework7 Svelte
Q: Can we have saturnframework integrations with other frameworks?

3.As your website says, its hard to learn and f# is more useful for finance applications
Q: can we have a saturnFinstack where all payment gateways are pre-integrated and ready to use?

4.i'd be super excited to see saturnframework to become a platform of choice for enterprise applications someday like
https://abp.io/

**Comment by cartermp** [comment]
This isn't a bug report or feature request, and discusses several things outside the scope of this project, so I'll close it.
