### ISSUE TITLE
Controller CustomOperation suggestions

### ISSUE THREAD

**Issue by panesofglass** [SaturnFramework/Saturn#37]
I think you could reduce some of the cognitive overhead of things like `task { return! ... }` with custom operations for model binding against a context or returning a result in the form of a known media type. I would love to hear what you have already tried and will try to find an opportunity to implement a prototype to show how I think this might work. It may require you change the `ControllerState` to always use `Task<_>`, if it doesn't already.

**Comment by Krzysztof-Cieslak** [comment]
I think that returning normal F# types from the operations in `controller` and automatically serializing them to right data format (based on required `Content-Type`) would be really nice and goes with my idea of `controller` being "higher level abstraction".

**Comment by NinoFloris** [comment]
Would this work with overloads or different operations?

**Comment by Krzysztof-Cieslak** [comment]
Overloads are not working with custom operations... I think.

**Comment by Nhowka** [comment]
Probably could work on a next version of the language. The implementation works, but I need to create some tests and other stuff to make sure it is behaving well in a lot of cases.

Sadly I never create tests, so that is very hard... I accept help: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1056-allow-custom-operation-overloads.md

**Comment by panesofglass** [comment]
I forgot about this issue until just now. You can overload `CustomOperation` by simply [adding overload methods (same name) _without the attribute_](https://github.com/panesofglass/computation-expressions-workshop/blob/master/exercises/08_EDSLs.md#overloading). See the NOTE in that linked section.

**Comment by Krzysztof-Cieslak** [comment]
So for this issue we currently have 2 things:

1. We have some overloads for controller functions - each controller action has additional overload in which they can get their Dependencies from DI container. - sample https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Controller.fs#L128-L134

2. We don't handle that by overloads but we have automatic "conversions" for common types - please take a look at `Controller.response` function - https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/ControllerHelpers.fs#L48-L102
