### ISSUE TITLE
OWIN + SignalR?

### ISSUE THREAD

**Issue by Thorium** [SaturnFramework/Saturn#41]
This is a question more than issue:

How do I integrate existing Owin-pipeline to Saturn, and does Saturn support SignalR?

**Comment by isaacabraham** [comment]
I would suggest looking on the Giraffe docs for that as Saturn is just an abstraction layer above that (and Giraffe itself just sits on top of ASP .NET Core). If either of those support it, then you can do it directly in those. I guess someone could always build a Saturn abstraction layer to support for SignalR...

**Comment by Krzysztof-Cieslak** [comment]
As I've mentioned in documentation, some kind of abstraction layer on top of web sockets is planned. Not sure if it will use SignalR, tho. 

For the OWIN piepline integration - as far as I understand Giraffe whole Giraffe application is single midleware pipeline from ASP.NET point of view, and there is no easy way to mix other midleware pieplines into Giraffe app. But asking this question on Giraffe repo, may be good idea :)
