### ISSUE TITLE
Can't use `set_body` in pipeline CE

### ISSUE THREAD

**Issue by johannesegger** [SaturnFramework/Saturn#47]
`set_body` referes to an overloaded member of `PipelineBuilder` and [it looks like](https://github.com/fsharp/fslang-suggestions/issues/69) overloaded members can't be used in CEs. The compiler has to say the following about that:

> The custom operation 'set_body' refers to a method which is overloaded. The implementations of custom operations may not be overloaded.

 Is it possible to just rename the overload that works on strings to something like `set_string_body` or `set_body_from_string`?

**Comment by Nhowka** [comment]
Now that F# 6.0 supports overloads on CEs by default, should we consider _unfixing_ this issue?
