### ISSUE TITLE
Provide a way to access the IWebHostBuilder

### ISSUE THREAD

**Issue by mexx** [SaturnFramework/Saturn#48]
I want to test stuff using the `TestServer` from `Microsoft.AspNetCore.TestHost`.
However it requires a `IWebHostBuilder`, which is not accessible when using the `application` CE.
It would be great when there would be a way to put Saturn application under tests easily.

**Comment by mexx** [comment]
One possibility would be to move the call to `.Build()` from the CE into the `run` function. But it's a breaking change.

**Comment by Krzysztof-Cieslak** [comment]
It's still pretty early in the days of the project so I'm open to breaking changes. Also it shouldn't be too painful - the only thing most people do with result of `application` CE is piping it to `run`, and moving `.Build()` won't break such code.
