### ISSUE TITLE
Make CEs more intellisense friendly 

### ISSUE THREAD

**Issue by vasily-kirichenko** [SaturnFramework/Saturn#51]
Currently it's impossible to see what custom operations are available:

![image](https://user-images.githubusercontent.com/873919/39646300-9eb9d5fa-4fe3-11e8-8b3d-183d6087d911.png)

**Comment by vasily-kirichenko** [comment]
Related issue https://youtrack.jetbrains.com/issue/RIDER-15832

**Comment by Krzysztof-Cieslak** [comment]
Related discussion - #16 

I do think it's tooling problem, not really Saturn's CE problem. Any ideas how we could make them more "intellisense friendly" ?

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/4831

**Comment by vasily-kirichenko** [comment]
If you are sorting completion items by kind in Ionide, it should just work after updating FCS.
