### ISSUE TITLE
Getting error when running build.sh

### ISSUE THREAD

**Issue by mrkaspa** [SaturnFramework/Saturn#52]
I got this error when setting up the project from the saturn template, looks like it's related to the paket.exe version

```
Error: SecureChannelFailure (The authentication or decryption has failed.) (Github - cached (temporarily ignore updates))
```

**Comment by forki** [comment]
Are you on mono? Can you please update mono?

Michel Perez <notifications@github.com> schrieb am Sa., 5. Mai 2018, 05:16:

**Comment by lmortimer** [comment]
FYI: The default Mono that is in the Ubuntu 18.04 LTS repositoriy is version 4.6.2 and you will encounter this error. 

Remove this version and install the latest as per instructions on the [Mono Website](https://www.mono-project.com/download/stable/). Paket then runs.

I saw this ticket when searching for the 'Error: SecureChannelFailure ...' so hopefully other people will see this.

**Comment by mrkaspa** [comment]
I updated mono and worked
