### ISSUE TITLE
Inconsistency in controller route signatures

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#57]
Some controller routes e.g. `show` use a tupled form for ctx and key. Other routes use curried form. Is there a reason why we have tupled form sometimes?

**Comment by isaacabraham** [comment]
In addition, in the Controller, the arguments for `controller.json` are inverted compared to just `json`.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #68
