### ISSUE TITLE
Add Windows Auth support in the ApplicationBuilder

### ISSUE THREAD

**Issue by ChrSteinert** [SaturnFramework/Saturn#62]
I would like to configure Windows Auth, similar to how currently OAuth or JWT tokens can be configured.
Currently, Kestrel does not support Windows Auth, so IIS or HttpSys has to be used. IIS can be configured, but HttpSys is currently completely missing (is it?)

Therefore I would like to have
1. an option to configure HttpSys
2. configure Windows Auth on ISS/HttpSys.

I already started playing around with possible implementations [H E R E](https://github.com/ChrSteinert/Saturn/commit/e71227ef07651d7918070d46be4d86c635b21e56)
, but I am not at all happy with the APIs yet and would love some advice on how to do the API and pursue an implementation.

### Downsides
Implementing this will create an additional dependency on the `Microsoft.AspNetCore.Server.HttpSys` package.

**Comment by Nhowka** [comment]
About the downside. As most of the features are on computation expressions, you could have it in a different package, adding a new extension method to the relevant CE and it would just work. That would make the feature optional yet transparent.

**Comment by ChrSteinert** [comment]
Ahh. Awesome. Was not aware you could extend CEs. Thanks for pointing this out!

________________________________

**Comment by Krzysztof-Cieslak** [comment]
In general problem of handling "extensions" in interesting one (and it's not about only this suggestion but I've also talked with @forki  who needed Redis caching). I think what I want to do is create directory in this repo that will contain extensions in form of `.fs` file + `paket.dependencies` file - this way you can add extension with paket file ref and paket will also add deps of your extension to the project.

**Comment by ChrSteinert** [comment]
I have added an "extension" implementing this [here](https://github.com/ChrSteinert/Saturn/tree/master/src/Saturn.HttpSys). @Krzysztof-Cieslak - if you could have a look if that is what you had in mind? I also added [a sample](https://github.com/ChrSteinert/Saturn/tree/master/sample/WindowsAuthSample).

**Comment by Krzysztof-Cieslak** [comment]
You also need `paket.dependencies` file next to `.fs` to make Paket's GitHub deps work - https://fsprojects.github.io/Paket/github-dependencies.html#Remote-dependencies

However, maybe just releasing NuGet packages is better idea? this way we don't couple framework with Paket. 

CC: @forki @isaacabraham Any opinions?

**Comment by Nhowka** [comment]
I vote for releasing nuget packages, easier and could just have the extension on the references and Saturn would be get as a dependency. Much cleaner and friendlier.

**Comment by Nhowka** [comment]
This is what we did on [Fable.Remoting](https://github.com/Zaid-Ajaj/Fable.Remoting/tree/0584fa02664236344aebc12ddc628f32ff4610f0/Fable.Remoting.Saturn) before migrating it all to a computation expression based API. Worked well enough as a nuget package.

**Comment by isaacabraham** [comment]
Personally I prefer github files for these kind of lightweight things - single files etc. They can be changed more easily than a nuget package, and I think is especially useful whilst we're in a kind of exploration phase. They could even be part of this repo a folder or branch with each extension in its own sub folder.

**Comment by Krzysztof-Cieslak** [comment]
Hey, sorry for delay.

I think I we should go with NuGet packages - this way we're not tightly coupled to one Paket's feature (and I guess most of those extensions will be simple enough that if someone prefers file dependency than they should be able to use it) and makes it easier for 3rd party extensions. 

@ChrSteinert, if you want to add extension to this repo put it in `src/Saturn.HttpSys` folder and send PR. I'll be happy to publish it from here.
