### ISSUE TITLE
XML documentation not yet being generated

### ISSUE THREAD

**Issue by rmunn** [SaturnFramework/Saturn#76]
https://github.com/SaturnFramework/Saturn/pull/36 set `GenerateDocumentationFile` in the Saturn.fsproj file, with the intent of generating the XML docs so that tooltips would be visible in, e.g., Ionide.

However, https://github.com/SaturnFramework/Saturn/commit/1edfbd391f03010d8036230e57c22e621dc41519 later removed `GenerateDocumentationFile` from the .fsproj file, so the Saturn NuGet package (as of 0.5.0) does not have XML doc tooltips.

I suspect that some tool, perhaps Forge, stripped `GenerateDocumentationFile` when recreating the .fsproj file and nobody noticed.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/SaturnFramework/Saturn/commit/22260348e8d86e0f31d9060523b295fed4ffe080
