### ISSUE TITLE
Which "direction" should OAuth claims be mapped?

### ISSUE THREAD

**Issue by rmunn** [SaturnFramework/Saturn#77]
The [`use_github_oauth` operation](https://github.com/SaturnFramework/Saturn/blob/afa32d03f7dd5864edf0b742c5df5a207830d242/src/Saturn/Application.fs#L269) in the `application` builder currently takes a `jsonToClaimMap`, which is a sequence of string pairs (key and value). The name `jsonToClaimMap` implies that the key should be the name of the key that will be found in the JSON object, and the value should be the name that will be used in the ASP.Net ClaimPrincipal. The code iterates through the `jsonToClaimMap` and calls `fun (k,v) -> opt.ClaimActions.MapJsonKey(k,v)` for each pair of strings. The implication of the name, then, is that MapJsonKey is being called with `(jsonKey, claimKey)`. E.g., if I'm [looking up the currently-authenticated user info at GitHub](https://developer.github.com/v3/users/#get-the-authenticated-user), I might want to map the `login` key from that JSON to a `githubUsername` claim in my ClaimsPrincipal, and the `name` key to a `fullName` claim. So based on the `jsonToClaimsMap` name, I'd expect to write the following in my `application` CE:

```
use_github_oauth "myClientId" "myClientSecret" "/github_oauth_callback" ["login", "githubUsername"; "name", "fullName"]
```

However, the [MapJsonKey documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.claimactioncollectionmapextensions.mapjsonkey?view=aspnetcore-2.1#Microsoft_AspNetCore_Authentication_ClaimActionCollectionMapExtensions_MapJsonKey_Microsoft_AspNetCore_Authentication_OAuth_Claims_ClaimActionCollection_System_String_System_String_) gives the parameter order as `(string claimType, string jsonKey)`. Which means that if I pass `["login", "githubUsername"; "name", "fullName"]` in as `jsonToClaimsMap`, what will happen is that a `githubUsername` key will be looked for (and not found) in the JSON, and if it was found it would be mapped to a `login` claim: the opposite of what was intended.

I believe that the order of the parameters in `opt.ClaimActions.MapJsonKey` needs to be swapped; e.g., this line:

```fsharp
jsonToClaimMap |> Seq.iter (fun (k,v) -> opt.ClaimActions.MapJsonKey(k,v) )
```

needs to become:

```fsharp
jsonToClaimMap |> Seq.iter (fun (k,v) -> opt.ClaimActions.MapJsonKey(v,k) )
```

(Also, `jsonToClaimMap` is not yet documented at https://saturnframework.github.io/docs/api/application/#use_github_oauth, so that also needs to happen).

**Comment by Krzysztof-Cieslak** [comment]
Yes, I do agree. It's a bug.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/SaturnFramework/Saturn/commit/d2e46b486888dd2fd91b79739302a659f7828634. I've also added comment to clarify what format should be used.
