### ISSUE TITLE
Update path used inside POST Choose instead of Create path

### ISSUE THREAD

**Issue by NinoFloris** [SaturnFramework/Saturn#79]
https://github.com/SaturnFramework/Saturn/blob/0d708fad64191e31b842dec5c7a5826b5f367887/src/Saturn/Controller.fs#L144 Bad copy paste?

Also any problems with some centralization of this logic? just yield! a list from a func into there

**Comment by Krzysztof-Cieslak** [comment]
This is POST into `/:id`, calling update sounds fine.

**Comment by NinoFloris** [comment]
Ok so then the other possibility I had in mind is true, there is no sitemap being added for Create handler then.

**Comment by NinoFloris** [comment]
NVM I'm blind
