### ISSUE TITLE
Subtraction of Actions

### ISSUE THREAD

**Issue by NinoFloris** [SaturnFramework/Saturn#91]
For things like user registration you only have create that should be accessible without authentication while all the other actions require auth. 
As it's a bit long and error prone I suggest we add subtraction to Action for these cases.
Action semantics are very close to a set anyway and Set already supports `-` and `+` so the operator choice seems in line with the framework. 

It would look like this example:
```fs
controller {
    plug (All - Create - Add) requireAuth
}
```     
Code is very simple and can be based around sets, just have to convert it back to list afterwards again because we can't have overloads 🙌 .
Added `+` as a brain dump as well but as it would only be a competing synonym to the list syntax I'm not comfortable putting that forward. 

I think maybe validation for `+` is also a bit too restrictive but for subtraction failing on `All` is probably a wise thing in terms of developer oversight/error.

```fs
  type Action =
    | Index
    | Show
    | Add
    | Edit
    | Create
    | Update
    | Patch
    | Delete
    | DeleteAll
    | All
    static member private AllSet = Set [Index;Show;Add;Edit;Create;Update;Patch;Delete;DeleteAll]
    static member private ThrowOnAll arg message action =
      match action with
      | All -> invalidArg arg message
      | _ -> action
    static member (-) (all: Action, subtract: Action) =
      match all with
      | All ->
        subtract
        |> Action.ThrowOnAll "subtract" "Invalid to subtract 'All' from 'All'."
        |> (fun x -> Action.AllSet |> Set.remove x |> Set.toList)
      | _ -> invalidOp "Actions can only subtract from 'All'."

    static member (-) (actions: Action list, subtract: Action) =
      subtract
      |> Action.ThrowOnAll "subtract" "Invalid to subtract 'All' from actions."
      |> (fun x -> Set actions |> Set.remove x |> Set.toList)

    static member (+) (action: Action, addition: Action) =
      let action = Action.ThrowOnAll "action" "Invalid to add anything to 'All', just use 'All'." action
      let addition = Action.ThrowOnAll "addition" "Invalid to add 'All' to anything, just use 'All'." addition
      Set [action] |> Set.add addition |> Set.toList

    static member (+) (actions: Action list, addition: Action) =
      if Set actions = Action.AllSet then invalidArg "actions" (sprintf "Invalid to add '%s', actions already add up to 'All'." (addition.ToString()))
      let addition = Action.ThrowOnAll "addition" "Invalid to add 'All' to anything, just use 'All'." addition

      Set actions |> Set.add addition |> Set.toList
```

Feedback is welcome

/cc: @forki @rmunn @baronfel @isaacabraham

**Comment by Krzysztof-Cieslak** [comment]
I'm not sure if i like it TBF. I see why such functionality is needed but I'm not fan of overloading operators like that.

Maybe something like `plug (except [Create; Add]) requireAuth` where `except` subtracts from `AllSet` given list

**Comment by NinoFloris** [comment]
That's a good way to go at it too, the concept we need any solution for is all that I care about.

**Comment by NinoFloris** [comment]
Will do after patch is merged 🙃
