### ISSUE TITLE
Can't use multiple OAuth sources in same application: "Scheme already exists: Cookies"

### ISSUE THREAD

**Issue by rmunn** [SaturnFramework/Saturn#93]
If a Web app wants to offer an end user multiple choices for authentication, for example offering both a "Log in with Google" and a "Log in with GitHub" button, it would be nice if all they had to do was this:

```fsharp
let app = application {
    // ...
    use_google_oauth googleClientId googleClientSecret "/oauth_callback_google" []
    use_github_oauth githubClientId githubClientSecret "/oauth_callback_github" []
}
```

However, trying that results in a runtime error from ASP.Net Core:

> System.InvalidOperationException: Scheme already exists: Cookies

The culprit is the following lines in OAuth.fs, found in both the `use_google_oauth` and `use_github_oauth` CE operations:

```fsharp
        s.AddAuthentication(fun cfg ->
          cfg.DefaultScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultSignInScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultChallengeScheme <- "Google")  // Or "GitHub"
         .AddCookie()
         .AddGoogle(fun opt ->  // Or ".AddGitHub"
           // ...
```

The only solution I've found so far is to ensure that `.AddCookie()` is only called once, no matter how many `use_foo_oauth` operations the library user puts in their application. For example, the following ugly hack worked for my test app, allowing both Google and GitHub authentication. Modify OAuth.fs to look like this:

```fsharp
module Saturn

open (lots of namespaces)

let mutable cookiesAlreadyAdded = false

type ApplicationBuilder with
    [<CustomOperation("use_google_oauth")>]
    member __.UseGoogleAuth(state: ApplicationState, clientId : string, clientSecret : string, callbackPath : string, jsonToClaimMap : (string * string) seq) =
      let middleware (app : IApplicationBuilder) =
        app.UseAuthentication()

      let service (s : IServiceCollection) =
        let b = s.AddAuthentication(fun cfg ->
          cfg.DefaultScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultSignInScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultChallengeScheme <- "Google")
        if not cookiesAlreadyAdded then
         b.AddCookie() |> ignore
         cookiesAlreadyAdded <- true
        b.AddGoogle(fun opt ->
          // Etc.
    // ...
    [<CustomOperation("use_github_oauth")>]
    member __.UseGithubAuth(state: ApplicationState, clientId : string, clientSecret : string, callbackPath : string, jsonToClaimMap : (string * string) seq) =
      let middleware (app : IApplicationBuilder) =
        app.UseAuthentication()

      let service (s : IServiceCollection) =
        let b = s.AddAuthentication(fun cfg ->
          cfg.DefaultScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultSignInScheme <- CookieAuthenticationDefaults.AuthenticationScheme
          cfg.DefaultChallengeScheme <- "GitHub")
        if not cookiesAlreadyAdded then
         b.AddCookie() |> ignore
         cookiesAlreadyAdded <- true
        b.AddOAuth("GitHub", fun (opt : Authentication.OAuth.OAuthOptions) ->
          // Etc.
```

Another possible solution would involve keeping the `cookiesAlreadyAdded` flag in the CE state object somewhere, though that's not ideal either since it means that the ApplicationBuilder in Saturn would need to have a property that's only used by the Saturn.Extensions.Authentication package — not exactly a clean separation of concerns. I haven't found a solution that I'm 100% happy with yet, but at least I've been able to confirm that the ugly hack works.

**Comment by Krzysztof-Cieslak** [comment]
`.AddCookie()` is also called in `Application.fs` (`use_custom_oauth`) so in this case it maybe be good idea to just add it to CE state.

**Comment by rmunn** [comment]
... Huh, so it is. I had assumed that all OAuth-related operations had been moved to Saturn.Extensions.Authorization, but I see now that it's just the 3rd-party OAuth operations.

There's also `use_cookies_authentication` and `use_cookies_authentication_with_config` to consider. And https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x mentions "multiple instances of cookie authentication" as a possibility, so there's probably a better way to distinguish between the various .AddCookie() calls that I just didn't figure out in my limited testing. I did try `.AddCookie("Google")` and so on, but it's apparently more complicated than that and I don't understand Asp.Net Core well enough (yet) to figure out the right approach.

**Comment by NinoFloris** [comment]
@rmunn of course multiple cookies are possible but not desired in this case, you don't want a cookie per social integration, you want the current login to overwrite the previous login cookie/state. So one service registration for an 'application' cookie is enough. 

Example of when you want/need multiple cookies https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/IdentityServiceCollectionExtensions.cs#L51

**Comment by Krzysztof-Cieslak** [comment]
I think that default behavior should assume that user wants only one cookie - that's what should happen in most cases. Fixed in https://github.com/SaturnFramework/Saturn/commit/d91aff34b78904a32e0c62db5b38fe86f09fe75f
