### ISSUE TITLE
New "except" function doesn't handle "All"

### ISSUE THREAD

**Issue by rmunn** [SaturnFramework/Saturn#97]
Writing `plug (except [All]) someHandler` would be extremely silly since it would be a no-op (`except [All]` should return an empty list of actions), but someone's going to do it at some point. Or else they'll do something like `plug (except [Index;All])` or something. Currently, `except [All]` would return `[Index;Show;Add;Edit;Create;Update;Patch;Delete;DeleteAll]`, which is the exact opposite of what it should return. If someone is silly enough to call `except [All]`, they should get an empty list of actions.

**Comment by NinoFloris** [comment]
Thanks, was a silly oversight indeed
