### ISSUE TITLE
Should Saturn suggest using Canopy for testing?

### ISSUE THREAD

**Issue by rmunn** [SaturnFramework/Saturn#99]
[Canopy](https://lefthandedgoat.github.io/canopy/index.html) is a nice DSL for automated Web app testing (via Selenium) that, IMHO, should get more attention than it's gotten so far. I believe it would make a good addition to the Saturn template, but before I start a PR against the template, I'd like to open a discussion first. Does Canopy fit well with the Saturn philosophy and/or the SAFE stack? Should it be added to the template, or just mentioned in the docs as a recommendation but not added to the template?

**Comment by forki** [comment]
Yes canopy fits well with SAFE-Stack. We already use it in the bookstore
sample

Robin Munn <notifications@github.com> schrieb am Di., 10. Juli 2018, 06:22:

**Comment by Krzysztof-Cieslak** [comment]
I definitely want to mention Canopy in Saturn docs, I've also considered generating Canopy tests as part of the scaffolding we do with `Saturn.Dotnet`

**Comment by Krzysztof-Cieslak** [comment]
Probably the big issues for adding Canopy to scaffolding/template is fact it's still requiring mono

**Comment by Krzysztof-Cieslak** [comment]
I'm stupid - Canopy supports Core

**Comment by Krzysztof-Cieslak** [comment]
Closing this one - I think it's good idea to support/promote Canopy. But this needs to be handled in template, documentation and in code generator. Nothing to do with core library.
